name: Hello GitHub Actions
on:
  push:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Python version
        run: python --version
      - name: Git version
        run: git --version
      - name: Current directory
        run: pwd
      - name: Show Files
        run: ls -la